apps/user/urls.py
from django.urls import path
from . views import profile_view

app_name = 'user'

urlpatterns = [
    path('profile', profile_view, name='profile_view'),

]

apps/web/urls.py
from django.urls import path
from . views import index_view, contact_view

app_name = 'web'

urlpatterns = [
    path('', index_view, name="index_view"),
    path('contact', contact_view, name="contact_view"),

]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('', include('apps.web.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, )
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, )

apps/notification/models.py
from django.db import models
from django.contrib.auth.models import User


class Notification(models.Model):
    name = models.CharField(max_length=30)
    content = models.CharField(max_length=200)

    def __str__(self):
        return self.name

apps/user/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.web.models import TimeStamp


class Profile(TimeStamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', editable=False)
    bio = models.TextField(null=True)
    present_work_space = models.CharField(max_length=100, null=True)
    live_country = models.CharField(max_length=30, null=True)
    gender = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.user.username

apps/web/models.py
from django.db import models
from django.contrib.auth.models import User


class TimeStamp(models.Model):
    """
    This is custom timestamp model :
        For inheritance to all model
    """

    created = models.DateTimeField('created at', auto_now_add=True)
    updated = models.DateTimeField('updated at', auto_now=True)

    class Meta:
        abstract = True


class Product(models.Model):
    user = models.ManyToManyField(User, related_name='product')
    name = models.CharField(max_length=50)
    price = models.IntegerField()

    def __str__(self):
        return self.name

apps/user/forms.py
from django import forms
from . models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user',)

apps/web/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    surname = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=50)
    phone = forms.IntegerField()
    message = forms.CharField(max_length=50)

apps/notification/views.py
from django.shortcuts import render

# Create your views here.

apps/user/views.py
from django.shortcuts import render
from apps.user.forms import ProfileForm
from apps.web.models import Product


def profile_view(request):
    products = Product.objects.filter(user=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
    else:
        form = ProfileForm(instance=request.user.profile)

    context = {'form': form,
               'products': products}

    return render(request, 'user/user_dashboard.html', context)

apps/web/views.py
from . forms import ContactForm
from django.core.mail import send_mail
from django.contrib import messages
from django.shortcuts import render, redirect
from django.conf import settings


def index_view(request):
    return render(request, 'web/index.html')


def contact_view(request):
    form = ContactForm(request.POST)
    if request.method == 'POST':
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        data = f'Name: {name}, Surname: {surname}, Email: {email}, Phone: {phone}, Message: {message}'

        send_mail(
            "You have a message from your site",
            data,
            settings.EMAIL_HOST_USER,
            ['ilkine2191@gmail.com'],
            fail_silently=False,
        )
        messages.success(request, 'Your message has been sent!')
        return redirect(request.META['HTTP_REFERER'])

    context = {'form': form}

    return render(request, "web/contact.html", context=context)

templates/user/user_dashboard.html
<!DOCTYPE html>

{% load crispy_forms_tags %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>User Dashboard</title>
</head>


<body>


    <form method="post" action="{% url 'user:profile_view' %}">
        {% csrf_token %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-8">


                    <h1 class="mt-4" align="center">Hello {{ request.user }}</h1>
                    <br>
                    <h1 class="mt-4" align="center" id="notifications" ></h1>

                    <hr class="mt-4 mb-5">

                    <h4 class="mt-4" align="center">Edit your profile .</h4>


                    <hr class="mt-4 mb-5">

                    {{ form|crispy }}

                    <button type="submit" class="btn btn-success">Submit</button>

                </div>

            </div>
        </div>
    </form>


    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="mt-4" align="center">Products</h1>
                <hr class="mt-4 mb-5">
                <h4 class="mt-4" align="center">Look up your basket .</h4>
                <hr class="mt-4 mb-5">

                <div class="container">
                    {% for product in products %}
                        <h3>Product name : {{ product.name }}, Product price : {{ product.price }} USD
                        </h3>
                    {% endfor %}
                </div>

                <br><br><br>

            </div>

        </div>
    </div>


    <script>
        const notifySocketLink =  `ws://127.0.0.1:8000/ws/notification/`
        const notificationSocket = new WebSocket(notifySocketLink);
        notificationSocket.onmessage = function(e) {

            const data = JSON.parse(e.data);
            const notifyShowDiv = document.getElementById("notifications")
            notifyShowDiv.textContent = data.notification
            //gelen datani duzgun otuzdurmalisan notificationun icine.
            console.log(data)
        };
    </script>



    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>




</body>

</html>

templates/web/contact.html
{% load crispy_forms_tags %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Contact Us</title>
</head>


<body>
    <form method="post" action="{% url 'web:contact_view' %}">
        {% csrf_token %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <h1 class="mt-4" align="center">Hello {{ request.user }}</h1>
                    <hr class="mt-4 mb-5">
                    <h4 class="mt-4" align="center">Send message to us .</h4>
                    <hr class="mt-4 mb-5">

                    {{ form|crispy }}

                    <button type="submit" class="btn btn-success">Send</button>
                </div>
            </div>
        </div>
    </form>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/web/index.html
<html lang="en">

<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Index</title>
</head>


<body>
    <div class="container">
            <div class="row justify-content-center">
                <button type="submit" class="btn btn-success"> <a href="{% url 'account_signup' %}">SIGNUP</a> </button>
                <button type="submit" class="btn btn-success"> <a href="{% url 'account_login' %}">LOGIN</a></button>
                <button type="submit" class="btn btn-success"> <a href="{% url 'web:contact_view' %}">CONTACT US</a></button>
            </div>
    </div>
</body>

</html>